apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-api
  labels:
    app: aura-api
spec:
  selector:
    matchLabels:
      app: aura-api
  template:
    metadata:
      labels:
        app: aura-api
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: api
        image: aura-api
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: aura-app-configmap
        - secretRef:
            name: aura-app-secret
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
