// <auto-generated />
using System;
using Aura.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aura.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260727004449_RenameClassicTemplate")]
    partial class RenameClassicTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aura.Core.Models.Accomplice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymized_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymized");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_accomplices");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_accomplices_event_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_accomplices_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_accomplices_token_hash");

                    b.ToTable("accomplices", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.DataRetentionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("ScheduledDeleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_delete_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_data_retention_jobs");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_data_retention_jobs_event_id");

                    b.HasIndex("ScheduledDeleteAt", "Status")
                        .HasDatabaseName("ix_data_retention_jobs_scheduled_delete_at_status");

                    b.ToTable("data_retention_jobs", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.DeliveryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_status");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("message_type");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_message_id");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_delivery_logs");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_delivery_logs_event_id");

                    b.HasIndex("DeliveryStatus", "Channel")
                        .HasDatabaseName("ix_delivery_logs_delivery_status_channel");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_delivery_logs_entity_type_entity_id");

                    b.ToTable("delivery_logs", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoupleNames")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("couple_names");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<DateTimeOffset>("EventEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_end_date");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("font_family");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hero_image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoGalleryUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_gallery_url");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("primary_color");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("secondary_color");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("ThankYouMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thank_you_message");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VenueAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("venue_address");

                    b.Property<decimal?>("VenueLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("venue_lat");

                    b.Property<decimal?>("VenueLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("venue_lng");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue_name");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("EventDate")
                        .HasDatabaseName("ix_events_event_date");

                    b.HasIndex("EventEndDate")
                        .HasDatabaseName("ix_events_event_end_date");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_events_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_events_status");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_events_template_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_events_user_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymized_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("InviteStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("invite_status");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymized");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_guests");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_guests_event_id");

                    b.HasIndex("EventId", "Category")
                        .HasDatabaseName("ix_guests_event_id_category");

                    b.HasIndex("EventId", "Email")
                        .HasDatabaseName("ix_guests_event_id_email");

                    b.ToTable("guests", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_status");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SentVia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sent_via");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_invitations_event_id");

                    b.HasIndex("GuestId")
                        .HasDatabaseName("ix_invitations_guest_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token_hash");

                    b.HasIndex("DeliveryStatus", "SentVia")
                        .HasDatabaseName("ix_invitations_delivery_status_sent_via");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.LiveMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccompliceId")
                        .HasColumnType("uuid")
                        .HasColumnName("accomplice_id");

                    b.Property<string>("CustomMessage")
                        .HasColumnType("text")
                        .HasColumnName("custom_message");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_status");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("MessageTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_template_id");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SentVia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sent_via");

                    b.HasKey("Id")
                        .HasName("pk_live_messages");

                    b.HasIndex("AccompliceId")
                        .HasDatabaseName("ix_live_messages_accomplice_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_live_messages_event_id");

                    b.HasIndex("MessageTemplateId")
                        .HasDatabaseName("ix_live_messages_message_template_id");

                    b.ToTable("live_messages", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_message");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<bool>("RequiresSwipe")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_swipe");

                    b.HasKey("Id")
                        .HasName("pk_message_templates");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_message_templates_event_id");

                    b.ToTable("message_templates", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_event_id");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_stripe_payment_intent_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.Rsvp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attendance")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("attendance");

                    b.Property<string>("DietaryRestrictions")
                        .HasColumnType("text")
                        .HasColumnName("dietary_restrictions");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<bool>("NeedsTransport")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_transport");

                    b.Property<bool>("PlusOne")
                        .HasColumnType("boolean")
                        .HasColumnName("plus_one");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rsvps");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_rsvps_event_id");

                    b.HasIndex("GuestId")
                        .HasDatabaseName("ix_rsvps_guest_id");

                    b.HasIndex("InvitationId")
                        .IsUnique()
                        .HasDatabaseName("ix_rsvps_invitation_id");

                    b.HasIndex("EventId", "Attendance")
                        .HasDatabaseName("ix_rsvps_event_id_attendance");

                    b.ToTable("rsvps", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layout_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("preview_url");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_templates_category");

                    b.ToTable("templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "wedding",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A classic and elegant design with floral touches.",
                            IsPremium = false,
                            LayoutJson = "{}",
                            Name = "Classic Aura",
                            PreviewUrl = "/assets/templates/classic.jpg"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "wedding",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Clean lines and ample whitespace for a contemporary look.",
                            IsPremium = false,
                            LayoutJson = "{}",
                            Name = "Modern Minimalist",
                            PreviewUrl = "/assets/templates/modern.jpg"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "wedding",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Warm and inviting, perfect for country or outdoor weddings.",
                            IsPremium = false,
                            LayoutJson = "{}",
                            Name = "Rustic Charm",
                            PreviewUrl = "/assets/templates/rustic.jpg"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "wedding",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Luxurious gold accents for a premium feel.",
                            IsPremium = true,
                            LayoutJson = "{}",
                            Name = "Premium Gold",
                            PreviewUrl = "/assets/templates/premium.jpg"
                        });
                });

            modelBuilder.Entity("Aura.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymized_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("HashedMagicLinkToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hashed_magic_link_token");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymized");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("HashedMagicLinkToken")
                        .HasDatabaseName("ix_users_hashed_magic_link_token");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.UserConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consent_type");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("terms_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_user_consents");

                    b.HasIndex("UserId", "ConsentType")
                        .HasDatabaseName("ix_user_consents_user_id_consent_type");

                    b.ToTable("user_consents", (string)null);
                });

            modelBuilder.Entity("Aura.Core.Models.Accomplice", b =>
                {
                    b.HasOne("Aura.Core.Models.Event", "Event")
                        .WithMany("Accomplices")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accomplices_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Aura.Core.Models.DataRetentionJob", b =>
                {
                    b.HasOne("Aura.Core.Models.Event", "Event")
                        .WithOne("DataRetentionJob")
                        .HasForeignKey("Aura.Core.Models.DataRetentionJob", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_data_retention_jobs_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Aura.Core.Models.DeliveryLog", b =>
                {
                    b.HasOne("Aura.Core.Models.Event", "Event")
                        .WithMany("DeliveryLogs")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_logs_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Aura.Core.Models.Event", b =>
                {
                    b.HasOne("Aura.Core.Models.Template", "Template")
                        .WithMany("Events")
                        .HasForeignKey("TemplateId")
                        .HasConstraintName("fk_events_templates_template_id");

                    b.HasOne("Aura.Core.Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_users_user_id");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aura.Core.Models.Guest", b =>
                {
                    b.HasOne("Aura.Core.Models.Event", "Event")
                        .WithMany("Guests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guests_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Aura.Core.Models.Invitation", b =>
                {
                    b.HasOne("Aura.Core.Models.Event", "Event")
                        .WithMany("Invitations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_events_event_id");

                    b.HasOne("Aura.Core.Models.Guest", "Guest")
                        .WithMany("Invitations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_guests_guest_id");

                    b.Navigation("Event");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Aura.Core.Models.LiveMessage", b =>
                {
                    b.HasOne("Aura.Core.Models.Accomplice", "Accomplice")
                        .WithMany("LiveMessages")
                        .HasForeignKey("AccompliceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_live_messages_accomplices_accomplice_id");

                    b.HasOne("Aura.Core.Models.Event", "Event")
                        .WithMany("LiveMessages")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_live_messages_events_event_id");

                    b.HasOne("Aura.Core.Models.MessageTemplate", "MessageTemplate")
                        .WithMany("LiveMessages")
                        .HasForeignKey("MessageTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_live_messages_message_templates_message_template_id");

                    b.Navigation("Accomplice");

                    b.Navigation("Event");

                    b.Navigation("MessageTemplate");
                });

            modelBuilder.Entity("Aura.Core.Models.MessageTemplate", b =>
                {
                    b.HasOne("Aura.Core.Models.Event", "Event")
                        .WithMany("MessageTemplates")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_templates_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Aura.Core.Models.Payment", b =>
                {
                    b.HasOne("Aura.Core.Models.Event", "Event")
                        .WithOne("Payment")
                        .HasForeignKey("Aura.Core.Models.Payment", "EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Aura.Core.Models.Rsvp", b =>
                {
                    b.HasOne("Aura.Core.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rsvps_events_event_id");

                    b.HasOne("Aura.Core.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rsvps_guests_guest_id");

                    b.HasOne("Aura.Core.Models.Invitation", "Invitation")
                        .WithOne("Rsvp")
                        .HasForeignKey("Aura.Core.Models.Rsvp", "InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rsvps_invitations_invitation_id");

                    b.Navigation("Event");

                    b.Navigation("Guest");

                    b.Navigation("Invitation");
                });

            modelBuilder.Entity("Aura.Core.Models.UserConsent", b =>
                {
                    b.HasOne("Aura.Core.Models.User", "User")
                        .WithMany("Consents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_consents_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aura.Core.Models.Accomplice", b =>
                {
                    b.Navigation("LiveMessages");
                });

            modelBuilder.Entity("Aura.Core.Models.Event", b =>
                {
                    b.Navigation("Accomplices");

                    b.Navigation("DataRetentionJob");

                    b.Navigation("DeliveryLogs");

                    b.Navigation("Guests");

                    b.Navigation("Invitations");

                    b.Navigation("LiveMessages");

                    b.Navigation("MessageTemplates");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Aura.Core.Models.Guest", b =>
                {
                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("Aura.Core.Models.Invitation", b =>
                {
                    b.Navigation("Rsvp");
                });

            modelBuilder.Entity("Aura.Core.Models.MessageTemplate", b =>
                {
                    b.Navigation("LiveMessages");
                });

            modelBuilder.Entity("Aura.Core.Models.Template", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Aura.Core.Models.User", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
