apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-frontend
  labels:
    app: aura-frontend
spec:
  selector:
    matchLabels:
      app: aura-frontend
  template:
    metadata:
      labels:
        app: aura-frontend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: frontend
        image: aura-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
