apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-retention-worker
  namespace: aura
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: data-retention-worker
        spec:
          imagePullSecrets:
          - name: ghcr-secret
          containers:
          - name: worker
            image: aura-workers-dataretention:latest
            envFrom:
            - configMapRef:
                name: aura-app-configmap
            - secretRef:
                name: aura-app-secret
            - secretRef:
                name: api-secrets
          restartPolicy: OnFailure
