apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-worker-email
  labels:
    app: aura-worker-email
spec:
  selector:
    matchLabels:
      app: aura-worker-email
  template:
    metadata:
      labels:
        app: aura-worker-email
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: worker
        image: aura-worker-email
        envFrom:
        - configMapRef:
            name: aura-app-configmap
        - secretRef:
            name: aura-app-secret
        env:
        - name: Smtp__Host
          value: "aura-mailhog"
        - name: Smtp__Port
          value: "1025"
        - name: Smtp__Username
          value: ""
        - name: Smtp__Password
          value: ""
