apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-worker-ssg
  labels:
    app: aura-worker-ssg
spec:
  selector:
    matchLabels:
      app: aura-worker-ssg
  template:
    metadata:
      labels:
        app: aura-worker-ssg
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: worker
        image: aura-worker-ssg
        envFrom:
        - configMapRef:
            name: aura-app-configmap
        - secretRef:
            name: aura-app-secret
