apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-worker-whatsapp
  labels:
    app: aura-worker-whatsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aura-worker-whatsapp
  template:
    metadata:
      labels:
        app: aura-worker-whatsapp
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: worker
        image: aura-worker-whatsapp
        envFrom:
        - configMapRef:
            name: aura-app-configmap
        - secretRef:
            name: aura-app-secret
