apiVersion: v1
kind: Secret
metadata:
  name: aura-app-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=aura-postgres;Port=5432;Database=auradb;Username=aura;Password=secretpassword"
  Minio__AccessKey: "admin"
  Minio__SecretKey: "secretpassword"
  Jwt__Key: "c3VwZXJzZWNyZXRqd3RzaWduYXR1cmVrZXkxMjM0NTY="
