apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aura-ingress
  namespace: aura
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: aura-api
                port:
                  number: 80
          - path: /e
            pathType: Prefix
            backend:
              service:
                name: aura-microsite-proxy
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aura-frontend
                port:
                  number: 80